### ISSUE TITLE
When the variable declaration form is opened, it pop-ups the types

### ISSUE THREAD

**Issue by nipunayf** [wso2/product-ballerina-integrator#1727]
### Description

$title. See the video below.

https://github.com/user-attachments/assets/373da3df-03b2-4bd0-98cb-a7dfd3d63c13

### Steps to Reproduce

1. Open a flow diagram that contains a variable declaration.
2. Open the variable declaration.

### Version

1.4.0.rc2

**Comment by axewilledge** [comment]
Should be fixed with this: https://github.com/wso2/vscode-extensions/pull/931

**Comment by pasindufernando1** [comment]
Will be released with 1.5.2

**Comment by KCSAbeywickrama** [comment]
Re-open due to the issue still reproducing when defining a new variable
